Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1

    end

    config.vm.define "sponda-a" do |spondaA|
        spondaA.vm.hostname = "sponda-a"
        spondaA.vm.network "private_network", ip: "192.168.1.2"
         spondaA.vm.provision "shell", inline: <<-SHELL
            apt update
            apt install -y podman
        SHELL
    end

    config.vm.define "sponda-b" do |spondaB|
        spondaB.vm.hostname = "sponda-b"
        spondaB.vm.network "private_network", ip: "192.168.1.3"
        spondaB.vm.provision "shell", inline: <<-SHELL
            apt update
            apt install -y podman
        SHELL
    end
end