---
# Play eseguito su tutti gli host che configura il file access.conf secondo una whitelist
- name: Configura il file access.conf secondo una whitelist
  hosts: all
  become: true
  
  # vars: keyword Ansible per definire variabili nello scope del play
  vars:
    # Lista degli users da mettere nella whitelist
    users_list:
      - alessio
      - giggetto
      - pippo
      - paperino
      
  # Lista dei Task da eseguire sugli host target
  tasks:
  # Primo Task   
    - name: Aggiunge gli utenti in whitelist al file di configurazione access
      ansible.builtin.blockinfile:             # Modulo dedicato a gestire sezioni dei file di configurazione
        path: /etc/security/access.conf        # Parametro path del modulo

        # lookup richiama la funzione Jinja che permette di recuperare dati da un risorsa esterna al playbook
        block: "{{ lookup('template', 'templates/whitelist.j2') }}"
        insertbefore: “- : ALL : ALL”  # Parametro del modulo blockinfile
