Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1

    end

    config.vm.define "ubuntu1" do |ubuntu1|
        ubuntu1.vm.hostname = "ubuntu1"
        ubuntu1.vm.network "private_network", ip: "192.168.1.2"
    end

    config.vm.define "ubuntu2" do |ubuntu2|
        ubuntu2.vm.hostname = "ubuntu2"
        ubuntu2.vm.network "private_network", ip: "192.168.1.3"
    end
end